name: kidpro
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.12=hb885b13_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - appnope==0.1.4
      - asttokens==3.0.1
      - certifi==2026.1.4
      - cfgv==3.5.0
      - click==8.3.1
      - comm==0.2.3
      - debugpy==1.8.19
      - decorator==5.2.1
      - distlib==0.4.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.20.3
      - fsspec==2026.1.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - hydra-core==1.3.2
      - identify==2.6.16
      - idna==3.11
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kidpro==0.1.0
      - librt==0.7.8
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.10.0
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathspec==1.0.3
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - pre-commit==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ruff==0.14.11
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segmentation-models-pytorch==0.5.0
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - stack-data==0.6.3
      - stringzilla==4.6.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==1.0.24
      - tomli==2.4.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - virtualenv==20.36.1
      - wcwidth==0.2.14
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/kidpro
