name: kidpro
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - expat=2.7.3=h50f4ffc_4
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - gdk-pixbuf=2.42.12=h0094380_1
  - gettext=0.21.0=hbdbcc25_2
  - icu=73.1=h313beb8_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libdicom=1.2.0=h6caf38d_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libglib=2.84.4=hcacd345_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.3=haa24f5a_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libsqlite=3.51.2=h1b79a29_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - openjpeg=2.5.4=h959fc53_1
  - openslide=4.0.0=hbc1fa79_4
  - openssl=3.0.18=h9b4081a_0
  - pcre2=10.46=h1dacb4a_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - python=3.10.12=hb885b13_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - accelerate==1.12.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - alembic==1.18.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - appnope==0.1.4
      - asttokens==3.0.1
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.78.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - distlib==0.4.0
      - docker==7.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.128.0
      - filelock==3.20.3
      - flask==3.1.2
      - flask-cors==6.0.2
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.47.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huey==2.6.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - identify==2.6.16
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==8.38.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kidpro==0.1.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librt==0.7.8
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mlflow==3.8.1
      - mlflow-skinny==3.8.1
      - mlflow-tracing==3.8.1
      - monai==1.5.1
      - mpmath==1.3.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.10.0
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openslide-python==1.4.3
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathspec==1.0.3
      - peft==0.18.1
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - pre-commit==4.5.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2026.1.15
      - requests==2.32.5
      - rsa==4.9.1
      - ruff==0.14.11
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segmentation-models-pytorch==0.5.0
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - stack-data==0.6.3
      - starlette==0.50.0
      - stringzilla==4.6.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.24
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.5
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - virtualenv==20.36.1
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/kidpro